### ISSUE TITLE
store: add PostgresSQL support

### ISSUE THREAD

**Issue by ortuman** [ortuman/jackal#36]
Implement postgres storage backend.

**Comment by robzon** [comment]
What's exactly needs to be done here? Since Squirrel is psql-compatible, is it only the database setup code that needs to be written? Are there things in storage/sql package that won't work with postgres?

Trying to asses how much work needs to be done, I'd give it a shot if I can fit it into my schedule.

**Comment by ortuman** [comment]
Also adapting sanetizers and sprecific platform statements such as “Insert or update”. A little help on this would be great. 

Currently I hope to start working on PEP ASAP.

**Comment by robzon** [comment]
I'll give it a shot. This is one of the very few things I can help with, since I'm not familiar with the XMPP protocol (yet).

**Comment by ortuman** [comment]
Implemented in ef9484b550e03ea5c5ef498d3a9083b469cbbc09

Thank you @robzon 🙌
