### ISSUE TITLE
how to manage users from an external script ?

### ISSUE THREAD

**Issue by beppe9000** [ortuman/jackal#95]
I would like to use an external server to provide authentication. Is there builtin support in jackal for any of these protocols? If not, has this been attempted before? 

If managing authentication externally is not feasible I was thinking of creating a php script exposing an HTTP API on the jackal server for the other server to manage users (create/disable/enable/set password).

What is the best way to tackle this without heavy modifications to both systems?

Thanks

**Comment by ortuman** [comment]
Unfortunately, and to date, there is no way to do external authentication that does not require a previous modification of jackal's code. 😞 

However, custom authentication mechanism via external gateway has been in the roadmap since long ago. 

Just to give you more context, currently i'm 100% focused on finishing XEP-0163 support (which I expect to have finished before ending this year), which will unlock OMEMO support for jackal server. 

But this sounds like a feature to be implemented afterwards. 😉 

Thanks for trusting & using jackal. 🙏

**Comment by beppe9000** [comment]
Thanks for the good work! I definitely think exposing a simple API for users and settings management would be helpful in many scenarios: for example what I wanted to do is to create and auto-login [converse.js](https://conversejs.org/) users like a forum chatbox. I have to work the client part too but everything starts from the server. ;)

**Comment by ortuman** [comment]
Here's the related feature issue:

https://github.com/ortuman/jackal/issues/82

Feel free to add any additional info. 😉

**Comment by ortuman** [comment]
👋 Hey @beppe9000! Let you know that [latest release](https://github.com/ortuman/jackal/releases/tag/v0.50.0) already offers support for external authentication mechanism.

Jackal provides this functionality through [grpc](https://grpc.io/). Authenticator [proto definition](https://github.com/jackal-xmpp/jackal-proto/blob/master/jackal/proto/authenticator/v1/authenticator.proto#L24-L27) can be found at [jackal-proto](https://github.com/jackal-xmpp/jackal-proto) repository.

In the example config file you can find an [snippet](https://github.com/ortuman/jackal/blob/master/example.config.yaml#L70-L74) that shows how to configure external auth integration. 

Please, if you have any doubt feel free to drop an issue or ping me on [gitter](https://gitter.im/jackal-im/jackal).

Thanks for you time 🙇

**Comment by beppe9000** [comment]
Nice, I didn't know of gRPC. It's a whole new world 👍🏻
